In [118]:
import pandas as pd
import numpy as np

In [119]:
mcf= pd.read_csv("data/mcf_clean_data.csv")
len(mcf)

22719

In [120]:
mcf.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]"
1,705309ff2a8d68b7ee215b6e2fc420ab,Manager (Facilities Management),Manager (Facilities Management),<p><strong >Role Overview</strong></p><p>We ar...,Role Overview We are seeking a Facilities Mana...,8,"[""Fire Safety"", ""Management Skills"", ""Sustaina...","[""Real Estate / Property Management""]","[""Permanent""]","[""Manager""]"
2,4a68226fc8b1d6f39bcf78451f7bc198,Sales Administrator,Sales Administrator,<ul>\n <li>Serve as administrator / key opera...,Serve as administrator / key operator for all ...,1,"[""Sales"", ""Microsoft Office"", ""Microsoft Excel...","[""Hospitality"", ""Sales / Retail""]","[""Full Time""]","[""Executive""]"
3,4726f24811127db6967fd1c07ec7ae77,Assistant Field Engineer(Construction),Assistant Field Engineer(Construction),<h3><strong>Our Company:</strong></h3>\n<p>Our...,Our Company: Our company develops ICT(Informat...,1,"[""Troubleshooting"", ""Construction"", ""Hardware""...","[""Customer Service"", ""Engineering"", ""Professio...","[""Full Time""]","[""Fresh/entry level""]"
4,301389565abb7d8ddd32efebb58776cf,Electronic Keyboard Teacher,Electronic Keyboard Teacher,<ul>\n <li>Teaching lessons to students at al...,Teaching lessons to students at all skill leve...,1,"[""Piano"", ""Classical"", ""Microsoft Excel"", ""Tea...","[""Education and Training""]","[""Full Time""]","[""Non-executive""]"

In [121]:
mcf.dtypes

uuid                      object
raw_title                 object
title                     object
raw_description           object
description               object
minimumYearsExperience     int64
skills                    object
categories                object
employmentTypes           object
positionLevels            object
dtype: object

In [122]:
mcf["positionLevels"].unique()

array(['["Junior Executive"]', '["Manager"]', '["Executive"]',
       '["Fresh/entry level"]', '["Non-executive"]', '["Professional"]',
       '["Senior Executive"]', '["Senior Management"]',
       '["Middle Management"]', '["Manager", "Executive"]',
       '["Middle Management", "Manager"]',
       '["Non-executive", "Fresh/entry level"]',
       '["Executive", "Fresh/entry level"]',
       '["Senior Management", "Manager"]'], dtype=object)

### Filter entry level and jobs with bachelor's degree

In [123]:
keywords = r"bachelor|degree|graduate|university|undergraduate|tertiary"
levels = r'"Fresh/entry level"|"Junior Executive"'

mcf_filtered1 = mcf[
    (
        (mcf["minimumYearsExperience"] == 0) |
        (mcf["positionLevels"].str.contains(levels, case=False, na=False))
    )
    &
    (mcf["description"].str.contains(keywords, case=False, na=False))
     & 
    (mcf["minimumYearsExperience"]<4)
   
]

mcf_filtered1.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]"
11,91dc337d5944663301fb1b60519c5e46,Outreach Operations and Data Analysis Executive,Outreach Operations and Data Analysis Executive,<p><strong>Working Days: </strong>5 days acros...,Working Days: 5 days across Monday - Sunday Lo...,0,"[""Tableau"", ""Data Analysis"", ""Big Data"", ""Inte...","[""Customer Service""]","[""Contract""]","[""Fresh/entry level""]"
50,7e67478b8d6e830db5e40c417833198f,Lecturer (Digital Journalism),Lecturer (Digital Journalism),"<p>Young and research-intensive, Nanyang Techn...","Young and research-intensive, Nanyang Technolo...",0,"[""Producing"", ""Multimedia"", ""Teaching"", ""Big D...","[""Education and Training""]","[""Full Time""]","[""Professional""]"
57,b83e84454e5aa753ab4d97b2de50480c,Vet Nurse,Vet Nurse,<p>🐾<strong> We’re Hiring: Veterinary Nurse</s...,🐾 We’re Hiring: Veterinary Nurse Location: Hol...,1,"[""Veterinary"", ""ICU"", ""Quality Improvement"", ""...","[""Healthcare / Pharmaceutical""]","[""Full Time""]","[""Junior Executive""]"
70,2a159f1e9bb5af1b43cc12be9b7f32c6,Project Engineer,Project Engineer,<p>The Role:</p><p>The candidate will coordina...,The Role: The candidate will coordinate projec...,1,"[""Microsoft Office"", ""Construction"", ""Drawing""...","[""Engineering""]","[""Full Time""]","[""Fresh/entry level""]"

In [124]:
len(mcf_filtered1)

1589

In [125]:
mcf_filtered1["minimumYearsExperience"].value_counts()

minimumYearsExperience
0    732
1    459
2    275
3    123
Name: count, dtype: int64

In [126]:
mcf_filtered1["positionLevels"].unique()

array(['["Junior Executive"]', '["Fresh/entry level"]',
       '["Professional"]', '["Non-executive"]', '["Senior Executive"]',
       '["Executive"]', '["Manager"]',
       '["Non-executive", "Fresh/entry level"]'], dtype=object)

### Save dataset

In [127]:
mcf_filtered1.to_csv("data/mcf_entrylevel.csv", index=False)

### 5 X 50 random

In [128]:
import pandas as pd

# sample 250 rows
sampled = mcf_filtered1.sample(n=250, random_state=42).copy()

# assign numbers 1–5 (50 rows each)
assignees = (
    [1]*50 +
    [2]*50 +
    [3]*50 +
    [4]*50 +
    [5]*50
)

sampled["assignee"] = assignees

# optional columns for your team
sampled["extracted_skills"] = ""
sampled["done"] = ""

sampled.to_csv("data/mcf_sample_250_assigned.csv", index=False)

sampled.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,assignee,extracted_skills,done
16193,72f3a5323583c1e9b2b12522de607f23,Manufacturing Engineer (Plastic) #79721,Manufacturing Engineer (Plastic) #79721,<p><strong>Job Description</strong></p><ul><li...,Job Description Industry/ Organization Type: M...,0,"[""Manufacturing Engineering"", ""Microsoft Offic...","[""Manufacturing"", ""Others""]","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",1,,
6278,b63e8aa0691815fcb3499e46cfbdad3d,Banking Sales Associate,Banking Sales Associate,<p><strong>Responsibilities:</strong></p>\n<p>...,Responsibilities: 1. Customer Engagement: - Bu...,0,"[""Wealth Management"", ""Training Management"", ""...","[""Banking and Finance""]","[""Full Time""]","[""Fresh/entry level""]",1,,
21601,bfb274c94e685dd864e8b83d833e0a8d,Research Assistant (Mapping Population Prefere...,Research Assistant (Mapping Population Prefere...,<p>Interested applicants are invited to apply ...,Interested applicants are invited to apply dir...,0,"[""Stata"", ""Qualitative data"", ""Community Healt...","[""Sciences / Laboratory / R&D""]","[""Full Time""]","[""Professional""]",1,,
3553,0761f72807ac9f4077b040343aa416c3,CNY Event Promoter@Takashimaya (NOW-15FEB) $12/hr,CNY Event Promoter@Takashimaya (NOW-15FEB) $12/hr,<p>CNY Event Promoter 年货海产销售员</p><p><br /></p>...,CNY Event Promoter 年货海产销售员 Responsibilities 职责...,0,"[""Sales"", ""Sampling"", ""Interpersonal Skills"", ...","[""Events / Promotions"", ""Sales / Retail""]","[""Temporary"", ""Contract"", ""Part Time""]","[""Non-executive""]",1,,
9737,944f523704ccb1367d7f2b4e40fd5cba,PART TIME ASSISTANT ART TEACHER,PART TIME ASSISTANT ART TEACHER,<p><strong>ART TEACHING ASSISTANT @ LyttleSpac...,ART TEACHING ASSISTANT @ LyttleSpace (Bedok So...,0,"[""Microsoft Office"", ""Painting"", ""Classroom"", ...","[""Design"", ""Education and Training""]","[""Part Time""]","[""Fresh/entry level""]",1,,

In [129]:
for i in range(1, 6):
    sampled[sampled["assignee"] == i].to_csv(
        f"data/jd{i}.csv", index=False
    )