In [16]:
import pandas as pd
import numpy as np

In [17]:
mcf= pd.read_csv("data/mcf_clean_data.csv")
len(mcf)

22719

In [18]:
mcf.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]"
1,705309ff2a8d68b7ee215b6e2fc420ab,Manager (Facilities Management),Manager (Facilities Management),<p><strong >Role Overview</strong></p><p>We ar...,Role Overview We are seeking a Facilities Mana...,8,"[""Fire Safety"", ""Management Skills"", ""Sustaina...","[""Real Estate / Property Management""]","[""Permanent""]","[""Manager""]"
2,4a68226fc8b1d6f39bcf78451f7bc198,Sales Administrator,Sales Administrator,<ul>\n <li>Serve as administrator / key opera...,Serve as administrator / key operator for all ...,1,"[""Sales"", ""Microsoft Office"", ""Microsoft Excel...","[""Hospitality"", ""Sales / Retail""]","[""Full Time""]","[""Executive""]"
3,4726f24811127db6967fd1c07ec7ae77,Assistant Field Engineer(Construction),Assistant Field Engineer(Construction),<h3><strong>Our Company:</strong></h3>\n<p>Our...,Our Company: Our company develops ICT(Informat...,1,"[""Troubleshooting"", ""Construction"", ""Hardware""...","[""Customer Service"", ""Engineering"", ""Professio...","[""Full Time""]","[""Fresh/entry level""]"
4,301389565abb7d8ddd32efebb58776cf,Electronic Keyboard Teacher,Electronic Keyboard Teacher,<ul>\n <li>Teaching lessons to students at al...,Teaching lessons to students at all skill leve...,1,"[""Piano"", ""Classical"", ""Microsoft Excel"", ""Tea...","[""Education and Training""]","[""Full Time""]","[""Non-executive""]"

In [19]:
mcf.dtypes

uuid                      object
raw_title                 object
title                     object
raw_description           object
description               object
minimumYearsExperience     int64
skills                    object
categories                object
employmentTypes           object
positionLevels            object
dtype: object

In [20]:
mcf["positionLevels"].unique()

array(['["Junior Executive"]', '["Manager"]', '["Executive"]',
       '["Fresh/entry level"]', '["Non-executive"]', '["Professional"]',
       '["Senior Executive"]', '["Senior Management"]',
       '["Middle Management"]', '["Manager", "Executive"]',
       '["Middle Management", "Manager"]',
       '["Non-executive", "Fresh/entry level"]',
       '["Executive", "Fresh/entry level"]',
       '["Senior Management", "Manager"]'], dtype=object)

### Filter to Entry level only

In [21]:
mcf_filtered = mcf[
    mcf["positionLevels"].str.contains("Fresh/entry level", na=False)
]

mcf_filtered.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels
3,4726f24811127db6967fd1c07ec7ae77,Assistant Field Engineer(Construction),Assistant Field Engineer(Construction),<h3><strong>Our Company:</strong></h3>\n<p>Our...,Our Company: Our company develops ICT(Informat...,1,"[""Troubleshooting"", ""Construction"", ""Hardware""...","[""Customer Service"", ""Engineering"", ""Professio...","[""Full Time""]","[""Fresh/entry level""]"
5,dd32ada5c76ba97526adf85326a58793,F&B Executive,F&B Executive,<p>The applicant would be tasked on the follow...,The applicant would be tasked on the following...,0,"[""Microsoft Excel"", ""Food Safety"", ""Quality As...","[""F&B""]","[""Full Time""]","[""Fresh/entry level""]"
11,91dc337d5944663301fb1b60519c5e46,Outreach Operations and Data Analysis Executive,Outreach Operations and Data Analysis Executive,<p><strong>Working Days: </strong>5 days acros...,Working Days: 5 days across Monday - Sunday Lo...,0,"[""Tableau"", ""Data Analysis"", ""Big Data"", ""Inte...","[""Customer Service""]","[""Contract""]","[""Fresh/entry level""]"
16,1f296d6da33fc7ce8d408b4cdccc5f8e,Installation Technician,Installation Technician,"<p>As our business expands, we’re seeking a sk...","As our business expands, we’re seeking a skill...",1,"[""Team Worker"", ""Preventive Maintenance"", ""Tro...","[""Engineering"", ""Manufacturing"", ""Professional...","[""Full Time""]","[""Fresh/entry level""]"
22,9f7f01d8e8e081eac94f0c3aca328ac7,Junior Marketing Crew - Entry Level/Training P...,Junior Marketing Crew - Entry Level/Training P...,"<p>If you are someone who is passionate, looki...","If you are someone who is passionate, looking ...",0,"[""Communication"", ""Customer Relationship"", ""Sa...","[""Advertising / Media"", ""Customer Service"", ""G...","[""Contract"", ""Full Time""]","[""Fresh/entry level""]"

### Number of rows and column type

In [22]:
len(mcf_filtered)

4156

In [23]:
mcf_filtered["positionLevels"].unique()

array(['["Fresh/entry level"]', '["Non-executive", "Fresh/entry level"]',
       '["Executive", "Fresh/entry level"]'], dtype=object)

### Save dataset

In [24]:
mcf_filtered.to_csv("data/mcf_entrylevel.csv", index=False)